name = "/cu:press"
description = "Press a single key or chord via execute_action(press_key)."

prompt = '''
You have the tools: execute_action.

Args:
- key:str    Examples: "Enter", "Escape", "Control+L", "Meta+L", "ArrowDown"

Behavior:
- Call execute_action("press_key", {"key": {{key|""}} }).
- Print result or stub warning.

Note: This action may be stubbed in your current MCP until implemented.
'''
[defaults]
key = "Enter"
