name = "/cu:scroll"
description = "Scroll vertically to a % (0..1000) via execute_action(scroll_to_percent)."

prompt = '''
You have the tools: execute_action.

Args:
- y:int  (0..1000)

Behavior:
- Call execute_action("scroll_to_percent", {"y": {{y|500}} }).
- Print status.

Note: This action may be a stub in your MCP until implemented.
'''
[defaults]
y = 500
